### ISSUE TITLE
'NoneType' object has no attribute 'get_paginator' when trying to open list of functions

### ISSUE THREAD

**Issue by BenWoodford** [revmischa/sublime-awslambda#3]
My credentials and region are set. Perhaps it's related to only having one function?

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "awslambda in /Users/ben/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 438, in run
  File "awslambda in /Users/ben/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 268, in select_function
  File "awslambda in /Users/ben/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 248, in _load_functions
AttributeError: 'NoneType' object has no attribute 'get_paginator'
```

**Comment by revmischa** [comment]
To me it looks like you have an older version of boto3 installed. Maybe system-wide?

**Comment by BenWoodford** [comment]
I followed the instructions for the AWS CLI stuff from brew (awscli, bin is aws) rather than boto. To my knowledge I don't have boto on here at all.

**Comment by revmischa** [comment]
Weird error, I don't think it could happen unless creds or region weren't set at some point. Patch above might help.

**Comment by BenWoodford** [comment]
Either that patch or a reinstall seems to have fixed it. Cheers!

Now I just need to work out why it thinks I can't use ListFunctions when I have AdministratorAccess on that IAM User. Possibly a propagation issue though.
